### ISSUE TITLE
Downloading thumbnails

### ISSUE THREAD

**Issue by ethen8181** [EthanRosenthal/rec-a-sketch#3]
Hi Ethan,

Do you happen to have the 200x200 pixel thumbnails for the models saved somewhere so we can download it without having to crawl it ourselves? Thanks!

I Tried doing 

```
python crawl.py config.yml --type thumbs
```

But it didn't download them to a file.

**Comment by EthanRosenthal** [comment]
The thumbnails are quite large and kind of a pain to move around - I'd rather not add them to the repo. The thumbnail crawling should work, though it is run via asynchronous commands which makes tracking down errors a major pain. Does anything get printed when you run the ```thumbs``` commdand? If you're comfortable diving into the code, you can pull everything outside of this ```with``` statement and refactor: https://github.com/EthanRosenthal/rec-a-sketch/blob/master/crawl.py#L240

One possibility could be that you may need to create the directory that stores the thumbnails before running the script. Following the ```config.yml.example``` file, you would need the following path to exist: ```rec-a-sketch/data/model_thumbs/```.

**Comment by ethen8181** [comment]
Thanks for the quick note! I think not creating the `model_thumbs` directory before running the crawl.py script might be the thing that's preventing it from functioning properly. I got it to work by just modifying this section of the code https://github.com/EthanRosenthal/rec-a-sketch/blob/master/flask_app/app/helpers.py#L145

I will close the issue for now.
