### ISSUE TITLE
df_to_matrix function does not return as expected

### ISSUE THREAD

**Issue by mgiangreco** [EthanRosenthal/rec-a-sketch#4]
df_to_matrix does not return sparse interactions matrix and index to ID mappers. 

For example:

In [1]: df = pd.DataFrame(np.random.randint(1,5,size=(100, 2)), columns=list('AB'))

In [2]: likes, uid_to_idx, idx_to_uid,\
mid_to_idx, idx_to_mid = df_to_matrix(df, 'A', 'B')

Traceback (most recent call last):

  File "<ipython-input-383-da8d339b6e7a>", line 1, in <module>
    likes, uid_to_idx, idx_to_uid,mid_to_idx, idx_to_mid = df_to_matrix(df, 'A', 'B')

TypeError: 'NoneType' object is not iterable

**Comment by EthanRosenthal** [comment]
I'm not sure why this didn't work for you. I ran exactly your code, and it worked fine. You can run the following in one line on the command line, and it'll make a fresh clone of the repo, load the libraries, and should run your command successfully:

```bash
git clone git@github.com:EthanRosenthal/rec-a-sketch.git && cd rec-a-sketch && python -c 'import numpy as np; import pandas as pd; from helpers import df_to_matrix; df = pd.DataFrame(np.random.randint(1,5,size=(100, 2)), columns=list("AB")); likes, uid_to_idx, idx_to_uid,mid_to_idx, idx_to_mid = df_to_matrix(df, "A", "B")'
```

**Comment by mgiangreco** [comment]
Got it, that worked for me. Also was able to bypass using the df_to_matrix function by using the following code from your post 1:

mid_to_idx = {}
idx_to_mid = {}
for (idx, mid) in enumerate(df_lim.mid.unique().tolist()):
    mid_to_idx[mid] = idx
    idx_to_mid[idx] = mid
    
uid_to_idx = {}
idx_to_uid = {}
for (idx, uid) in enumerate(df_lim.uid.unique().tolist()):
    uid_to_idx[uid] = idx
    idx_to_uid[idx] = uid


def map_ids(row, mapper):
    return mapper[row]

I = df_lim.uid.apply(map_ids, args=[uid_to_idx]).as_matrix()
J = df_lim.mid.apply(map_ids, args=[mid_to_idx]).as_matrix()
V = np.ones(I.shape[0])
likes = sparse.coo_matrix((V, (I, J)), dtype=np.float64)
likes = likes.tocsr()
